### ISSUE TITLE
Add default files

### ISSUE THREAD

**Issue by choonho** [sundarr786/private-registry#1]
For open-source repository, default recommended files are

* README
* LICENSE
* .gitignore

**Comment by sundarr786** [comment]
Hi choonho,

Thanks for the suggestion,
I have added above mentioned files.
In .gitignore file for now I added *.o and a filename only.

Please let me know , can I close this issue or if any changes need to be done.

Thanks,
Sundar

**Comment by choonho** [comment]
If you resolved the issue, closing issue is your task. Looks good. Please close.
